### ISSUE TITLE
motors not moving in right direction and forward

### ISSUE THREAD

**Issue by saurabhvyas** [stylixboom/lr_motor#1]
I am using tb6612fng , with yellow hobby grade motors and pi 3 , I have verified the connections , and also tested on arduino , while testing with arduino it moves perfectly forward / backward / left / right , but with pi 3 , its weird , right command doesnt work and forward doesnt work , backward and left work fine , I updated the nodejs file to reflect my gpio pin numbers , I have experienced the same problem with other motor drivers including drv8833 , any ideas ?

**Comment by saurabhvyas** [comment]
update : I found it , a single pin header was inserted at wrong place , It can get a little bit messy with so many wires and connections , thanks for your code!

**Comment by bwj555555** [comment]
Thanks for your test, and good to know it works on your end.

**Comment by stylixboom** [comment]
Thanks for your test and good to know it works on your end.
